-- ============================================================
-- Migration 005: Fix taxes column constraints (MySQL)
-- ============================================================
-- No-op for MySQL: the 001 schema already defines taxes.type correctly.
-- CHECK constraints in MySQL 8.0.16+ are enforced, but the column is VARCHAR
-- with no CHECK in our simplified MySQL schema (MySQL handles type validation
-- at the application layer).
