-- Migration 018: Add 'accepted' status to delivery_notes (MySQL)
-- When a delivery note is accepted (invoiced), its status changes to 'accepted'.
-- MySQL CHECK constraints can't be dropped/re-added as easily as PG.
-- In our MySQL schema we don't use CHECK constraints for status fields
-- (validation is handled at the application layer), so this is a no-op.
