-- Migration 019: Add 'completed' as valid status for sales_orders (MySQL)
-- In our MySQL schema we don't use CHECK constraints for status fields
-- (validation is handled at the application layer), so this is a no-op.
